name: CMake Build and Test

on:
  push:
    branches: [ complex-reactor ]
  pull_request:
    branches: [ complex-reactor ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Клонируем репозиторий
    - uses: actions/checkout@v3

    # 2. Устанавливаем зависимости (CMake, g++)
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++ make

    # 3. Удаляем старую build-папку на случай старого кэша
    - name: Clean previous build
      run: rm -rf build

    # 4. Настраиваем проект с помощью CMake
    - name: Configure CMake
      run: cmake -S . -B build

    # 5. Собираем проект
    - name: Build
      run: cmake --build build --config Release

    # 6. Запускаем тесты
    - name: Run tests
      run: ctest --output-on-failure --test-dir build
